### ISSUE TITLE
sever.jar 启动报错

### ISSUE THREAD

**Issue by lycohana** [Magma-Block/GuessingGameOnline#1]
java -jar "C:\Users\Dawn Dream\Desktop\GussingGame-Alpha-1\Server.jar"
Exception in thread "main" java.lang.NoClassDefFoundError: client/Command
        at server.GameServer.<init>(GameServer.java:10)
        at server.GameServer.main(GameServer.java:129)
Caused by: java.lang.ClassNotFoundException: client.Command
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 2 more

**Comment by Magma-Block** [comment]
已经没问题了 :)
